---
#driver:
#  name: vsphere

driver: 
  name: vsphere
  max_wait_until_ready: 30

transport:
  name: ssh
  max_wait_until_ready: 30

driver_config:
  username:  'chefdude' # [ssh user name of provisioned guest (default is root)]
  password:  'KnifesAreFun' # [ssh password of provisioned guest]
  authentication:
    #vsphere_username: # set this in .kitchen.local.yml [your vsphere server user name]
    #vsphere_password: # set this in .kitchen.local.yml [your vsphere server password]
    vsphere_server: 'eaclab-vcs01.itlab.ea.com' #[your vsphere server host name]
    # i got this by providing it and then running kitchen list, the error message returned this value
    vsphere_expected_pubkey_hash: '9ac7c56f460eca48df79ed1ec45d60aa4026008e05a6e33eeeb030a90bb40eac' #'[hash of your hosts public ssl key]
  server_create:
    datacenter: 'Burnaby' #[vsphere datacenter name where template is located]
    network_label: '10.9.176.0/23' # [vsphere network name to use]
    network_adapter_device_key: 4000 # [network key] (from comment on github)
    template_path: 'chef-kitchen-centos66' #[path to the template of vm to clone]

provisioner:
  name: chef_zero

platforms:
  - name: centos-kitchen

suites:
  - name: default
    run_list:
      - recipe[basic::default]
    attributes:
